# per-machines overrides
# put tweaks in ~/.config/alacritty/local.toml
general.import = ["~/.config/alacritty/local.toml"]

[env]
TERM = "xterm-256color"

[window]
dimensions.columns = 86
dimensions.lines = 28
padding.x = 10
padding.y = 10
opacity = 0.95

[font]
size = 14.0
normal.family = "Classic Console Neue"

[cursor]
style.shape = "Beam"
style.blinking = "On"

